apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-ui
  namespace: devops-cyber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-ui
  template:
    metadata:
      labels:
        app: review-ui
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: review-ui
          image: registry.gitlab.com/gfoldy/devops-cyber-project-1/review-ui:0.3
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ai-news-db
                  key: DATABASE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: review-ui
  namespace: devops-cyber
spec:
  selector:
    app: review-ui
  ports:
    - port: 80
      targetPort: 8080

